import { QuestionBank } from "../features/quiz/types";

/**
 * Draft 100 question bank mapped directly from the existing `rice.txt`.
 *
 * CRITICAL NOTICE:
 * - Line 69 in rice.txt is missing/marked as '?'
 * - No verified Chinese translations exist in the repo.
 * - reviewStatus is strictly 'draft' to block production release until audited.
 */
export const draft100QuestionBank: QuestionBank = {
  id: "rice-100-draft-v1",
  version: "0.9.0-draft",
  scoringVersion: "count-100-equal-v1",
  reviewStatus: "draft", // MUST remain draft until user provides official reviewed questions and translations
  sourceNote: 'Derived from rice.txt. Line 69 is marked "?". Unreviewed draft translation. Blocked from production release.',
  questions: [
    { id: "q001", order: 1, text: { en: "Held hands romantically?", "zh-CN": "曾与他人浪漫牵手？" } },
    { id: "q002", order: 2, text: { en: "Been on a date?", "zh-CN": "曾经约会？" } },
    { id: "q003", order: 3, text: { en: "Been in a relationship?", "zh-CN": "谈过恋爱？" } },
    { id: "q004", order: 4, text: { en: "Danced without leaving room for Jesus?", "zh-CN": "跳过贴身热舞？" } },
    { id: "q005", order: 5, text: { en: "Kissed a non-family member?", "zh-CN": "亲吻过非家人？" } },
    { id: "q006", order: 6, text: { en: "Kissed a non-family member on the lips?", "zh-CN": "亲吻过非家人的嘴唇？" } },
    { id: "q007", order: 7, text: { en: "French kissed?", "zh-CN": "接吻过（舌吻）？" } },
    { id: "q008", order: 8, text: { en: "French kissed in public?", "zh-CN": "在公共场合舌吻？" } },
    { id: "q009", order: 9, text: { en: "Kissed on the neck?", "zh-CN": "被亲吻或亲吻他人颈部？" } },
    { id: "q010", order: 10, text: { en: "Kissed horizontally?", "zh-CN": "躺着亲吻？" } },
    { id: "q011", order: 11, text: { en: "Given or received a hickey?", "zh-CN": "留下或被留下吻痕（草莓）？" } },
    { id: "q012", order: 12, text: { en: "Kissed or been kissed on the breast?", "zh-CN": "亲吻或被亲吻胸部？" } },
    { id: "q013", order: 13, text: { en: "Kissed someone below the belt?", "zh-CN": "亲吻过对方腰带以下部位？" } },
    { id: "q014", order: 14, text: { en: "Kissed for more than two hours consecutively?", "zh-CN": "连续接吻超过两小时？" } },
    { id: "q015", order: 15, text: { en: "Played a game involving stripping?", "zh-CN": "玩过涉及脱衣的游戏？" } },
    { id: "q016", order: 16, text: { en: "Seen or been seen by another person in a sensual context?", "zh-CN": "在私密情境下见过或被见过身体？" } },
    { id: "q017", order: 17, text: { en: "Masturbated?", "zh-CN": "自慰过？" } },
    { id: "q018", order: 18, text: { en: "Masturbated to a picture or video?", "zh-CN": "对着图片或视频自慰？" } },
    { id: "q019", order: 19, text: { en: "Masturbated while someone else was in the room?", "zh-CN": "房间里有其他人时自慰？" } },
    { id: "q020", order: 20, text: { en: "Been caught masturbating?", "zh-CN": "自慰时被当场撞见？" } },
    { id: "q021", order: 21, text: { en: "Masturbated with an inanimate object?", "zh-CN": "借助非生物道具自慰？" } },
    { id: "q022", order: 22, text: { en: "Seen or read pornographic material?", "zh-CN": "看过或读过色情作品？" } },
    { id: "q023", order: 23, text: { en: "Massaged or been massaged sensually?", "zh-CN": "进行或接受过私密按摩？" } },
    { id: "q024", order: 24, text: { en: "Gone through the motions of intercourse while fully dressed?", "zh-CN": "隔着衣物进行亲密模拟？" } },
    { id: "q025", order: 25, text: { en: "Undressed or been undressed by a MPS (member of the preferred sex)?", "zh-CN": "脱去或被心仪性别脱去衣物？" } },
    { id: "q026", order: 26, text: { en: "Showered with a MPS?", "zh-CN": "与心仪性别一同淋浴？" } },
    { id: "q027", order: 27, text: { en: "Fondled or had your butt cheeks fondled?", "zh-CN": "抚摸或被抚摸臀部？" } },
    { id: "q028", order: 28, text: { en: "Fondled or had your breasts fondled?", "zh-CN": "抚摸或被抚摸胸部？" } },
    { id: "q029", order: 29, text: { en: "Fondled or had your genitals fondled?", "zh-CN": "抚摸或被抚摸私处？" } },
    { id: "q030", order: 30, text: { en: "Had or given “blue balls”?", "zh-CN": "经历过未释放的生殖器充血胀痛？" } },
    { id: "q031", order: 31, text: { en: "Had an orgasm due to someone else’s manipulation?", "zh-CN": "通过他人抚弄达到高潮？" } },
    { id: "q032", order: 32, text: { en: "Sent a sexually explicit text or instant message?", "zh-CN": "发送过露骨性暗示短信或消息？" } },
    { id: "q033", order: 33, text: { en: "Sent or received sexually explicit photographs?", "zh-CN": "发送或接收过露骨私密照片？" } },
    { id: "q034", order: 34, text: { en: "Engaged in sexually explicit activity over video chat?", "zh-CN": "在视频通话中进行过露骨行为？" } },
    { id: "q035", order: 35, text: { en: "Cheated on a significant other during a relationship?", "zh-CN": "在恋爱关系中出轨？" } },
    { id: "q036", order: 36, text: { en: "Purchased contraceptives?", "zh-CN": "购买过避孕用品？" } },
    { id: "q037", order: 37, text: { en: "Gave oral sex?", "zh-CN": "进行过口交？" } },
    { id: "q038", order: 38, text: { en: "Received oral sex?", "zh-CN": "接受过口交？" } },
    { id: "q039", order: 39, text: { en: "Ingested someone else’s genital secretion?", "zh-CN": "吞咽过他人的生殖分泌物？" } },
    { id: "q040", order: 40, text: { en: "Used a sex toy with a partner?", "zh-CN": "与伴侣一同使用过情趣玩具？" } },
    { id: "q041", order: 41, text: { en: "Spent the night with a MPS?", "zh-CN": "与心仪性别共度一夜？" } },
    { id: "q042", order: 42, text: { en: "Been walked in on while engaging in a sexual act?", "zh-CN": "亲密行为时被人意外闯入撞见？" } },
    { id: "q043", order: 43, text: { en: "Kicked a roommate out to commit a sexual act?", "zh-CN": "为亲密行为而支开室友？" } },
    { id: "q044", order: 44, text: { en: "Ingested alcohol in a non-religious context?", "zh-CN": "非宗教情境下饮酒？" } },
    { id: "q045", order: 45, text: { en: "Played a drinking game?", "zh-CN": "玩过饮酒游戏？" } },
    { id: "q046", order: 46, text: { en: "Been drunk?", "zh-CN": "喝醉过？" } },
    { id: "q047", order: 47, text: { en: "Faked sobriety to parents or teachers?", "zh-CN": "向家长或老师假装清醒？" } },
    { id: "q048", order: 48, text: { en: "Had severe memory loss due to alcohol?", "zh-CN": "因饮酒发生严重断片？" } },
    { id: "q049", order: 49, text: { en: "Used tobacco?", "zh-CN": "吸过烟或使用烟草？" } },
    { id: "q050", order: 50, text: { en: "Used marijuana?", "zh-CN": "使用过大麻？" } },
    { id: "q051", order: 51, text: { en: "Used a drug stronger than marijuana?", "zh-CN": "使用过强于大麻的药物或毒品？" } },
    { id: "q052", order: 52, text: { en: "Used methamphetamine, crack cocaine, PCP, horse tranquilizers or heroin?", "zh-CN": "使用过冰毒、可卡因、PCP、氯胺酮或海洛因等违禁品？" } },
    {
      id: "q053",
      order: 53,
      text: { en: "Been sent to the office of a principal, dean or judicial affairs representative for a disciplinary infraction?", "zh-CN": "因违纪被叫到校长或院长办公室？" },
    },
    { id: "q054", order: 54, text: { en: "Been put on disciplinary probation or suspended?", "zh-CN": "受过纪律处分、留校察看或休学？" } },
    { id: "q055", order: 55, text: { en: "Urinated in public?", "zh-CN": "在公共场所小便？" } },
    { id: "q056", order: 56, text: { en: "Gone skinny-dipping?", "zh-CN": "裸泳过？" } },
    { id: "q057", order: 57, text: { en: "Gone streaking?", "zh-CN": "裸奔过？" } },
    { id: "q058", order: 58, text: { en: "Seen a stripper?", "zh-CN": "看过脱衣舞表演？" } },
    { id: "q059", order: 59, text: { en: "Had the police called on you?", "zh-CN": "曾有人针对你报警？" } },
    { id: "q060", order: 60, text: { en: "Run from the police?", "zh-CN": "从警察面前逃跑？" } },
    { id: "q061", order: 61, text: { en: "Had the police question you?", "zh-CN": "接受过警察盘问？" } },
    { id: "q062", order: 62, text: { en: "Had the police handcuff you?", "zh-CN": "被警方戴上手铐？" } },
    { id: "q063", order: 63, text: { en: "Been arrested?", "zh-CN": "被正式逮捕过？" } },
    { id: "q064", order: 64, text: { en: "Been convicted of a crime?", "zh-CN": "被判定有罪？" } },
    { id: "q065", order: 65, text: { en: "Been convicted of a felony?", "zh-CN": "被定重罪？" } },
    { id: "q066", order: 66, text: { en: "Committed an act of vandalism?", "zh-CN": "蓄意破坏公物？" } },
    { id: "q067", order: 67, text: { en: "Had sexual intercourse?", "zh-CN": "有过性交经历？" } },
    { id: "q068", order: 68, text: { en: "Had sexual intercourse three or more times in one night?", "zh-CN": "一晚性交三次或以上？" } },
    { id: "q069", order: 69, text: { en: "[Missing in source file rice.txt: ?]", "zh-CN": "【原文件 rice.txt 第 69 项缺失为 ?，待核实】" } },
    { id: "q070", order: 70, text: { en: "Had sexual intercourse 10 or more times?", "zh-CN": "性交 10 次或以上？" } },
    { id: "q071", order: 71, text: { en: "Had sexual intercourse in four or more positions?", "zh-CN": "尝试过四种或以上体位性交？" } },
    { id: "q072", order: 72, text: { en: "Had sexual intercourse with a stranger or person you met within 24 hours?", "zh-CN": "与认识不足24小时的人性交？" } },
    { id: "q073", order: 73, text: { en: "Had sexual intercourse in a motor vehicle?", "zh-CN": "在机动车内发生性交？" } },
    { id: "q074", order: 74, text: { en: "Had sexual intercourse outdoors?", "zh-CN": "在户外发生性交？" } },
    { id: "q075", order: 75, text: { en: "Had sexual intercourse in public?", "zh-CN": "在公共场所发生性交？" } },
    { id: "q076", order: 76, text: { en: "Had sexual intercourse in a swimming pool or hot tub?", "zh-CN": "在泳池或温泉浴缸中发生性交？" } },
    { id: "q077", order: 77, text: { en: "Had sexual intercourse in a bed not belonging to you or your partner?", "zh-CN": "在非双方所有的床上发生性交？" } },
    { id: "q078", order: 78, text: { en: "Had sexual intercourse while you or your partner’s parents were in the same home?", "zh-CN": "当父母在同处房屋内时发生性交？" } },
    { id: "q079", order: 79, text: { en: "Had sexual intercourse with non-participating third party in the same room?", "zh-CN": "在同一房间有未参与第三方时发生性交？" } },
    { id: "q080", order: 80, text: { en: "Joined the mile high club?", "zh-CN": "在飞机飞行期间发生性交（加入高空俱乐部）？" } },
    { id: "q081", order: 81, text: { en: "Participated in a “booty call” with a partner whom you were not in a relationship with?", "zh-CN": "非恋爱关系下的临时约炮？" } },
    { id: "q082", order: 82, text: { en: "Traveled 100 or more miles for the primary purpose of sexual intercourse?", "zh-CN": "以性交为主要目的出行超过100英里？" } },
    { id: "q083", order: 83, text: { en: "Had sexual intercourse with a partner with a 3 or more year age difference?", "zh-CN": "与年龄相差3岁或以上的伴侣性交？" } },
    { id: "q084", order: 84, text: { en: "Had sexual intercourse with a virgin?", "zh-CN": "与处女/处女性交？" } },
    { id: "q085", order: 85, text: { en: "Had sexual intercourse without a condom?", "zh-CN": "在未戴避孕套情况下性交？" } },
    { id: "q086", order: 86, text: { en: "Had a STI test due to reasonable suspicion?", "zh-CN": "因合理怀疑而进行性病筛查？" } },
    { id: "q087", order: 87, text: { en: "Had a STI?", "zh-CN": "确诊过性传播疾病？" } },
    { id: "q088", order: 88, text: { en: "Had a threesome?", "zh-CN": "参与过三人性行为？" } },
    { id: "q089", order: 89, text: { en: "Attended an orgy?", "zh-CN": "参加过群交聚会？" } },
    { id: "q090", order: 90, text: { en: "Had two or more distinct acts of sexual intercourse with two or more people within 24 hours?", "zh-CN": "24小时内与两位或以上不同对象性交？" } },
    { id: "q091", order: 91, text: { en: "Had sexual intercourse with five or more partners?", "zh-CN": "曾与五位或更多伴侣发生过性交？" } },
    { id: "q092", order: 92, text: { en: "Been photographed or filmed during sexual intercourse by yourself or others?", "zh-CN": "性交过程中被拍摄照片或录像？" } },
    { id: "q093", order: 93, text: { en: "Had period sex?", "zh-CN": "在经期发生性交？" } },
    { id: "q094", order: 94, text: { en: "Had anal sex?", "zh-CN": "发生过肛交？" } },
    { id: "q095", order: 95, text: { en: "Had a pregnancy scare?", "zh-CN": "经历过意外怀孕恐慌？" } },
    { id: "q096", order: 96, text: { en: "Impregnated someone or been impregnated?", "zh-CN": "致使他人怀孕或曾怀孕？" } },
    { id: "q097", order: 97, text: { en: "Paid or been paid for a sexual act?", "zh-CN": "进行过有偿性交易？" } },
    { id: "q098", order: 98, text: { en: "Committed an act of voyeurism?", "zh-CN": "有过偷窥行为？" } },
    { id: "q099", order: 99, text: { en: "Committed an act of incest?", "zh-CN": "有过乱伦行为？" } },
    { id: "q100", order: 100, text: { en: "Engaged in bestiality?", "zh-CN": "有过兽交行为？" } },
  ],
};
